"""
Hanime.tv API wrapper.

Flow:
1. Search: POST https://search.htv-services.com/
2. Video details: GET https://hanime.tv/api/v8/video?id={slug}
3. Real stream URLs: GET https://hanime.tv/api/v8/guest/videos/{id}/manifest
   - Requires WASM-generated x-signature + x-time headers
   - Returns videos_manifest with real m3u8s.highwinds-cdn.com stream URLs
   - Signature generated by: tools/get_signature.js (Node.js)
"""

import json
import logging
import os
import random
import re
import subprocess
import time
from html import unescape

import requests

log = logging.getLogger(__name__)

SEARCH_URL   = "https://search.htv-services.com/"
VIDEO_URL    = "https://hanime.tv/api/v8/video"
MANIFEST_URL = "https://hanime.tv/api/v8/guest/videos/{video_id}/manifest"
BASE_URL     = "https://hanime.tv"

_TOOLS_DIR  = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tools')
_SIG_SCRIPT = os.path.join(_TOOLS_DIR, 'get_signature.js')


class HanimeAPI:
    """Wrapper for hanime.tv's native API."""

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': (
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                'AppleWebKit/537.36 (KHTML, like Gecko) '
                'Chrome/124.0.0.0 Safari/537.36'
            ),
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
            'Origin': BASE_URL,
            'Referer': BASE_URL + '/',
        })
        self._last_request = 0
        self._sig_cache: dict = {}
        self._sig_ttl = 20  # signatures expire quickly — refresh every 20s

    # ── Signature generation ──────────────────────────────────────────

    def _get_signature(self) -> tuple[str, int]:
        """
        Run tools/get_signature.js via Node.js to get a fresh
        WASM-computed x-signature + x-time pair.
        """
        cached = self._sig_cache
        if cached and time.time() - cached.get('generated_at', 0) < self._sig_ttl:
            return cached['sig'], cached['stime']

        if not os.path.exists(_SIG_SCRIPT):
            raise RuntimeError(f"Signature script not found: {_SIG_SCRIPT}")

        log.info("Generating hanime.tv WASM signature...")
        try:
            result = subprocess.run(
                ['node', _SIG_SCRIPT],
                capture_output=True, text=True, timeout=15
            )
        except FileNotFoundError:
            raise RuntimeError("Node.js not found — install nodejs in Dockerfile")
        except subprocess.TimeoutExpired:
            raise RuntimeError("Signature generation timed out (>15s)")

        # Script prints multiple JSON lines; use the last valid one
        lines = [l.strip() for l in result.stdout.splitlines()
                 if l.strip().startswith('{"ssignature"')]
        if not lines:
            raise RuntimeError(
                f"No signature in output. stderr: {result.stderr[:300]}"
            )

        data  = json.loads(lines[-1])
        sig   = data['ssignature']
        stime = int(data['stime'])

        self._sig_cache = {'sig': sig, 'stime': stime, 'generated_at': time.time()}
        log.info(f"Signature ready: stime={stime}")
        return sig, stime

    def _auth_headers(self) -> dict:
        try:
            sig, stime = self._get_signature()
            return {
                'x-signature-version': 'web2',
                'x-signature': sig,
                'x-time': str(stime),
                'x-session-token': '',
                'x-user-license': '',
            }
        except Exception as e:
            log.warning(f"Could not get WASM signature: {e}. Continuing without.")
            return {}

    # ── HTTP helper ───────────────────────────────────────────────────

    def _request(self, method: str, url: str, **kwargs) -> dict:
        max_retries = 3
        last_error = None
        for attempt in range(max_retries):
            try:
                elapsed = time.time() - self._last_request
                if elapsed < 0.5:
                    time.sleep(0.5 - elapsed + random.uniform(0.1, 0.3))
                self._last_request = time.time()
                resp = self.session.request(method, url, timeout=30, **kwargs)
                resp.raise_for_status()
                return resp.json()
            except requests.exceptions.RequestException as e:
                log.warning(f"Request failed (attempt {attempt+1}/{max_retries}): {e}")
                last_error = e
                time.sleep(1 + attempt * 2)
        raise Exception(f"Failed after {max_retries} attempts. Last: {last_error}")

    # ── Public API ────────────────────────────────────────────────────

    def search(self, query: str, page: int = 0) -> list[dict]:
        """Search for hentai videos."""
        payload = {
            "search_text": query,
            "tags": [], "tags_mode": "AND",
            "brands": [], "blacklist": [],
            "order_by": "created_at_unix",
            "ordering": "desc",
            "page": page,
        }
        log.info(f"Searching hanime.tv for '{query}'")
        data = self._request("POST", SEARCH_URL, json=payload)

        hits_raw = data.get("hits", "[]")
        hits = json.loads(hits_raw) if isinstance(hits_raw, str) else hits_raw

        results = []
        for h in hits:
            results.append({
                'id':          h.get('id'),
                'slug':        h.get('slug', ''),
                'name':        h.get('name', ''),
                'title':       h.get('name', ''),
                'cover_url':   h.get('cover_url', ''),
                'poster_url':  h.get('poster_url', h.get('cover_url', '')),
                'cover':       h.get('cover_url', ''),
                'tags':        h.get('tags', []),
                'views':       h.get('views', 0),
                'brand':       h.get('brand', ''),
                'description': h.get('description', ''),
                'url':         f"{BASE_URL}/videos/hentai/{h.get('slug', '')}",
            })
        log.info(f"Found {len(results)} results for '{query}'")
        return results

    def details(self, slug: str) -> dict:
        """
        Get video details + real stream URLs.
        Always tries the signed manifest endpoint first.
        """
        log.info(f"Fetching details for '{slug}'")

        # Step 1: basic video info (metadata + fallback streams)
        data = self._request(
            "GET", VIDEO_URL,
            params={"id": slug},
            headers=self._auth_headers(),
        )
        video    = data.get("hentai_video", {})
        video_id = video.get("id")
        tags     = [t.get("text", "") for t in video.get("hentai_tags", [])]
        desc     = unescape(re.sub(r'<[^>]+>', '', video.get("description", ""))).strip()

        # Step 2: get real streams from signed manifest
        streams = []
        if video_id:
            try:
                streams = self._get_manifest_streams(video_id, slug)
                log.info(f"Manifest streams OK for {slug}: {len(streams)} streams")
            except Exception as e:
                log.warning(f"Manifest failed for {slug}: {e}")

        # Fallback: parse basic API streams (these will be fake streamable.cloud URLs)
        if not streams:
            log.warning(f"Using fallback streams for {slug} — URLs may be invalid")
            streams = self._parse_streams(data.get("videos_manifest", {}))

        # Episodes
        episodes = []
        for ep in video.get("hentai_franchise_hentai_videos", []):
            episodes.append({
                'id':        ep.get('id'),
                'slug':      ep.get('slug', ''),
                'name':      ep.get('name', ''),
                'title':     ep.get('name', ''),
                'cover_url': ep.get('cover_url', ''),
                'poster_url':ep.get('poster_url', ''),
            })

        return {
            'id':           video_id,
            'slug':         video.get('slug', slug),
            'name':         video.get('name', slug.replace('-', ' ').title()),
            'title':        video.get('name', slug.replace('-', ' ').title()),
            'description':  desc,
            'summary':      desc,
            'poster_url':   video.get('poster_url', ''),
            'cover_url':    video.get('cover_url', ''),
            'cover':        video.get('cover_url', ''),
            'tags':         tags,
            'genres':       tags,
            'brand':        video.get('brand', ''),
            'views':        video.get('views', 0),
            'likes':        video.get('likes', 0),
            'streams':      streams,
            'episodes':     episodes,
            'totalEpisodes':len(episodes),
            'url':          f"{BASE_URL}/videos/hentai/{video.get('slug', slug)}",
        }

    def get_streams(self, slug: str) -> dict:
        """Get streaming URLs for a video."""
        info    = self.details(slug)
        streams = info.get('streams', [])

        # Best = highest resolution
        best = None
        for s in streams:
            if not best or int(s.get('height', 0) or 0) > int(best.get('height', 0) or 0):
                best = s

        dl_url = best.get('url', '') if best else ''
        log.info(f"Sources for {slug}: dl_url={dl_url}, streams={len(streams)}")
        return {
            'streams': streams,
            'dl_url':  dl_url,
            'sources': [
                {'url': s['url'], 'label': f"{s['height']}p", 'type': s.get('extension', '')}
                for s in streams if s.get('url')
            ],
        }

    # ── Internal helpers ──────────────────────────────────────────────

    def _parse_streams(self, manifest: dict) -> list[dict]:
        """Parse videos_manifest structure into flat stream list."""
        streams = []
        for server in manifest.get("servers", []):
            for s in server.get("streams", []):
                url = s.get('url', '')
                if not url:
                    continue
                streams.append({
                    'url':             url,
                    'height':          s.get('height', ''),
                    'width':           s.get('width', 0),
                    'size_mbs':        s.get('filesize_mbs', 0),
                    'kind':            s.get('kind', ''),
                    'extension':       s.get('extension', ''),
                    'is_downloadable': s.get('is_downloadable', False),
                    'server':          server.get('name', ''),
                    'filename':        s.get('filename', ''),
                })
        return streams

    def _get_manifest_streams(self, video_id: int, slug: str) -> list[dict]:
        """
        Fetch GET /api/v8/guest/videos/{id}/manifest with a valid
        WASM-generated signature to get real CDN stream URLs.
        Response is plain JSON (not encrypted).
        """
        sig, stime = self._get_signature()

        headers = {
            'x-signature-version': 'web2',
            'x-signature': sig,
            'x-time': str(stime),
            'x-session-token': '',
            'x-user-license': '',
            'Accept': 'application/json',
            'Origin': BASE_URL,
            'Referer': f"{BASE_URL}/videos/hentai/{slug}",
        }

        url  = MANIFEST_URL.format(video_id=video_id)
        resp = self.session.get(url, headers=headers, timeout=15)

        if resp.status_code == 200:
            data = resp.json()
            if 'videos_manifest' in data:
                streams = self._parse_streams(data['videos_manifest'])
                if streams:
                    return streams
            log.debug(f"Manifest 200 but no streams: {str(data)[:200]}")

        elif resp.status_code == 401:
            raise RuntimeError(f"Manifest 401 — signature expired for video {video_id}")
        else:
            raise RuntimeError(f"Manifest HTTP {resp.status_code} for video {video_id}")

        return []
